class TransactionModel {
  final String id;
  final String title;
  final String type;
  final String descLine1;
  final String descLine2;
  final String amount;
  final String date;
  final bool isIncome;
  final String status;
  final String reference;

  TransactionModel({
    required this.id,
    required this.title,
    required this.type,
    required this.descLine1,
    required this.descLine2,
    required this.amount,
    required this.date,
    required this.isIncome,
    this.status = "Success",
    required this.reference,
  });
}

// Sample fallback list matching the reference design 100%
final List<TransactionModel> sampleTransactionsList = [
  TransactionModel(
    id: "1",
    title: "Direct Income",
    type: "Direct Income",
    descLine1: "₹300 received from 7989293968",
    descLine2: "Direct Referral Income • Cycle 1",
    amount: "300.00",
    date: "28 Aug 2026, 11:05 AM",
    isIncome: true,
    status: "Success",
    reference: "SR927281",
  ),
  TransactionModel(
    id: "2",
    title: "Single-Leg Income",
    type: "Single-Leg Income",
    descLine1: "₹200 received from Level 1 – Cycle 1",
    descLine2: "First Level Income Added to Main Wallet",
    amount: "200.00",
    date: "28 Aug 2026, 10:45 AM",
    isIncome: true,
    status: "Success",
    reference: "SR927282",
  ),
  TransactionModel(
    id: "3",
    title: "Fund Deposit",
    type: "Fund Deposit",
    descLine1: "₹1,200 added to Fund Wallet",
    descLine2: "Fund Request Approved by Admin",
    amount: "1,200.00",
    date: "28 Aug 2026, 09:30 AM",
    isIncome: true,
    status: "Success",
    reference: "SR927283",
  ),
  TransactionModel(
    id: "4",
    title: "ID Activation",
    type: "ID Activation",
    descLine1: "₹1,200 deducted from Fund Wallet",
    descLine2: "ID activated successfully – Cycle 1",
    amount: "1,200.00",
    date: "28 Aug 2026, 09:45 AM",
    isIncome: false,
    status: "Success",
    reference: "SR927284",
  ),
  TransactionModel(
    id: "5",
    title: "Fund Transfer",
    type: "Fund Transfer",
    descLine1: "₹500 transferred to 7989293968",
    descLine2: "From Fund Wallet",
    amount: "500.00",
    date: "28 Aug 2026, 12:15 PM",
    isIncome: false,
    status: "Success",
    reference: "SR927285",
  ),
  TransactionModel(
    id: "6",
    title: "Fund Received",
    type: "Fund Received",
    descLine1: "₹500 received from 7989293968",
    descLine2: "Added to Fund Wallet",
    amount: "500.00",
    date: "28 Aug 2026, 12:20 PM",
    isIncome: true,
    status: "Success",
    reference: "SR927286",
  ),
  TransactionModel(
    id: "7",
    title: "Cash Out Request",
    type: "Cash Out Request",
    descLine1: "₹1,000 withdrawal requested",
    descLine2: "Processing Fee: ₹150 | You Will Receive: ₹850",
    amount: "1,000.00",
    date: "28 Aug 2026, 01:10 PM",
    isIncome: false,
    status: "Pending",
    reference: "SR927287",
  ),
  TransactionModel(
    id: "8",
    title: "Cash Out Successful",
    type: "Cash Out Successful",
    descLine1: "₹1,000 withdrawn to UPI",
    descLine2: "Processing Fee: ₹150 | Net Received: ₹850",
    amount: "1,000.00",
    date: "28 Aug 2026, 06:35 PM",
    isIncome: false,
    status: "Success",
    reference: "SR927288",
  ),
  TransactionModel(
    id: "9",
    title: "Withdrawal Refund",
    type: "Withdrawal Refund",
    descLine1: "₹1,000 added back to Main Wallet",
    descLine2: "Previous withdrawal failed/rejected",
    amount: "1,000.00",
    date: "27 Aug 2026, 07:10 PM",
    isIncome: true,
    status: "Refunded",
    reference: "SR927289",
  ),
  TransactionModel(
    id: "10",
    title: "Mobile Recharge",
    type: "Mobile Recharge",
    descLine1: "Recharge ₹299 for 7989293968",
    descLine2: "Payment from Main Wallet",
    amount: "299.00",
    date: "27 Aug 2026, 05:25 PM",
    isIncome: false,
    status: "Success",
    reference: "SR9272810",
  ),
  TransactionModel(
    id: "11",
    title: "Electricity Bill Payment",
    type: "Electricity Bill Payment",
    descLine1: "Bill payment ₹750",
    descLine2: "Customer No: XXXXXX | Paid from Main Wallet",
    amount: "750.00",
    date: "27 Aug 2026, 04:40 PM",
    isIncome: false,
    status: "Success",
    reference: "SR9272811",
  ),
  TransactionModel(
    id: "12",
    title: "Cycle Top-Up (New Cycle)",
    type: "Cycle Top-Up (New Cycle)",
    descLine1: "₹1,200 deducted from Fund Wallet",
    descLine2: "Cycle 1 Completed → Cycle 2 Activated",
    amount: "1,200.00",
    date: "27 Aug 2026, 08:15 PM",
    isIncome: false,
    status: "Success",
    reference: "SR9272812",
  ),
];
